name: Post issue comment to Jira

on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find JIRA ticket in the issue body
        id: find_key
        run: |
          jira_id="$(echo "${{ github.event.issue.body }}" | grep -o -E '${{ vars.JIRA_PROJECT_KEY }}\-[0-9]+')"
          echo "jira_id=$jira_id" >> $GITHUB_OUTPUT

      - name: Comment on Jira issue
        uses: atlassian/gajira-comment@v3
        if: ${{ startsWith(steps.find_key.outputs.jira_id, format('{0}-', vars.JIRA_PROJECT_KEY)) }}
        with:
          issue: ${{ steps.find_key.outputs.jira_id }}
          comment: |
            ${{ github.event.comment.body }}
            
            -----
            GitHub comment: ${{ github.event.comment.html_url }}
